### ISSUE TITLE
Decisions page not rendering

### ISSUE THREAD

**Issue by aizzi** [structurizr/lite#22]
Hello Simon,

I'm experiencing a strange behavior with Structurizr Lite. I have the following folder structure:

```
.
├── architecture
│   ├── decisions
│   │   └── 0001-record-architecture-decisions.md
│   ├── documentation
│   │   └── 01-introduction.md
│   ├── workspace.dsl
```

This is the content of the files:

WORKSPACE.DSL
```
workspace "VAS Platform 2.x" "Architecture of the VAS Platform" {
    # Disabling implied relationships
    !impliedRelationships false

    # Structurizr specific references
    !docs documentation
    !adrs decisions

    model {
        #####################
        # Internal Entities #
        #####################
        enterprise "VAS Ecosystem" {
            ss_vasPlatform = softwareSystem "VAS Platform"
        }
    }

    views {
        ##########################################
        # Common styles for common look and feel #
        ##########################################
        #LND-01
        systemLandscape "lnd01" {
            title "LND-01: VAS Platform 2.x High Level Architecture"
            description "This diagram presents the whole echosystem of the VAS Platform from a logical point of view"
            include *
            exclude "element.tag==hidden"
            autoLayout "lr"
        }
    }
}
```

0001-record-architecture-decisions.md (created with ADR tool)
```
# 1. Record architecture decisions

Date: 2021-01-01

## Status

Accepted

## Context

We need to record the architectural decisions made on this project.

## Decision

We will use Architecture Decision Records, as [described by Michael Nygard](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions).

## Consequences

See Michael Nygard's article, linked above. For a lightweight ADR toolset, see Nat Pryce's [adr-tools](https://github.com/npryce/adr-tools).
```

01-introduction.md
```
## Overview and Goals
---

The high level architecture of the system, with regards to functionalities and logical components, is illustrated in the diagram below:

![](embed:lnd01)
```

I start Structurizr Lite from the root with the following command:

`docker run -d -it --rm -p 8080:8080 -v $PWD/architecture:/usr/local/structurizr --name structurizr structurizr/lite:latest`

Then I can see the diagrams, the documentation, but **I cannot see the decisions**.

This is a simplified version of my model, which is presented correctly on the Cloud.

I also have the `v1.x` of the model (same folder structure), which works fine locally **up to version 2875**, but refuses to load on any version newer than that.

`docker run -d -it --rm -p 8080:8080 -v $PWD/architecture:/usr/local/structurizr --name structurizr structurizr/lite:2875` ==> GOOD

`docker run -d -it --rm -p 8080:8080 -v $PWD/architecture:/usr/local/structurizr --name structurizr structurizr/lite:latest` ==> BAD

Funny enough, the simplified version I present here **does not work at all** on version 2875.

Both models are fine on the Cloud.

Thanks for helping

**Comment by simonbrowndotje** [comment]
This should now be fixed in 2919+.

**Comment by aizzi** [comment]
Yes, I confirm the new version works on the `v2.x` model.

I still have some weird behavior with the `v1.x` model, which I can see only if I use the version 2875 connected to port 8081. I suspect it has something to do with the JSESSIONID cookie, but wasn't able to pinpoint. Will open a new ticket when I will have more time to investigate. 

Thank you
